server:
  port: 19093

spring:
  application:
    name: es-service-provider
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    sentinel:
      transport:
        port: 8719
        ## 默认端口8080，已改为自定义18088端口，通过http://127.0.0.1:18088/#/dashboard访问
        dashboard: localhost:18088
      ##使用nacos配置中心存储限流规则
      datasource:
        ds0:
          nacos:
            data-id: ${spring.application.name}-flow-rules
            data-type: json
            group-id: DEFAULT_GROUP
            rule-type: flow
            server-addr: 127.0.0.1:8848
## 日志级别
logging:
  level:
    org:
      elasticsearch:
        client:
          RestClient: debug

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    sentinel:
      datasource:
        ds0:
          nacos:
            server-addr: nacos:8848
  elasticsearch:
    uris: http://elasticsearch:9200
  config:
    activate:
      on-profile: docker,dev

